version: "3.9"
#Docker Networks
networks:
  app_network:
    driver: bridge
services:

  #PHP Service
  app:
    container_name: app
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    working_dir: /var/www
    restart: unless-stopped
    tty: true
    environment:
       - APP_ENV=${APP_ENV}
    volumes:
      - ./:/var/www
      # - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      # - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - "9001:9000"
    networks:
      - app_network

  #Nginx Service
  webserver:
    image: nginx:1.25.1-alpine-slim
    container_name: webserver
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    links:
      - app
    depends_on:
      - app
    networks:
      - app_network

  #MySQL Service
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0.33
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bof_erp
      MYSQL_ROOT_PASSWORD: bof_erp_password
      MYSQL_USER: bof_erp_user
      MYSQL_PASSWORD: bof_erp_password
    networks:
      - app_network
volumes:
  dbdata:
    driver: local
