version: '3'

services:
  rupbot:
    container_name: rupbot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - APP_ENV=local
      #- DB_HOST=${DB_HOST}
      - DB_HOST=docker.for.mac.host.internal
      #- DB_HOST=host.docker.internal
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    tty: true
    volumes:
      - app_source:/var/www/html
      - storage_data:/var/www/html/storage
      - vendor_data:/var/www/html/vendor
    networks:
      - mynetwork
  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: nginx
    volumes:
      - app_source:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/
    restart: unless-stopped
    tty: true
    ports:
      - "8082:80"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  storage_data:
  vendor_data:
  app_source:
