services:
  rupbot:
    image: mdshajib/rupbot:latest
    tty: true
    restart: always
    volumes:
      - app_source:/var/www/html
      - storage_data:/var/www/html/storage
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    networks:
      - mynetwork
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
  nginx:
    image: nginx:1.25.1-alpine-slim
    volumes:
      - app_source:/var/www/html
      - ./rupbot/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - "80:80"
    hostname: rb.test
    depends_on:
      - rupbot
    networks:
      mynetwork:
        aliases:
        - rb.test
networks:
  mynetwork:
    driver: bridge
volumes:
  app_source:
  storage_data:
