version: "3.9"

services:

  #PHP Service
  rupbot:
    container_name: rupbot
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    working_dir: /var/www/rupbot
    # restart: unless-stopped
    environment:
      - APP_ENV=local
    tty: true
    # ports:
    #   - "9001:9000"
    volumes:
      - ./:/var/www/rupbot
    #   - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - webserver
    networks:
      - app_network

  #Nginx Service
  webserver:
    image: nginx:1.25.1-alpine-slim
    container_name: webserver
    volumes:
      - ./:/var/www/rupbot
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    networks:
      - app_network

  #MySQL Service
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0.33
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bof_erp
      MYSQL_ROOT_PASSWORD: bof_erp_password
      MYSQL_USER: bof_erp_user
      MYSQL_PASSWORD: bof_erp_password
    networks:
      - app_network

#Docker Networks
networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
