version: "3"

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - .:/var/www/app:delegated
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app:delegated
    networks:
      - laravel