name: Deploy Rupbot application

on:
  push:
    branches:
      - main

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_VERSION: "latest"
      DOCKER_IMAGE: "rupbot"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Login to Docker Hub
    #   run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    
    # - name: Build and push Docker image
    #   run: |
    #     docker build -t ${{ secrets.DOCKER_USER }}/${DOCKER_IMAGE}:latest .
    #     docker push ${{ secrets.DOCKER_USER }}/${DOCKER_IMAGE}:latest
    - name: Debug
      run: |
        ls -la

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "rupbot"
        target: "/root/rb"
    - name: Deploy to remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/rb
          # mv site.conf conf.d/
          docker ps -a
          # docker-compose up -d
