name: Deploy Rupbot application

on:
  push:
    branches:
      - main

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_VERSION: "latest"
      DOCKER_IMAGE: "rupbot"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p "${{ secrets.DOCKERHUB_TOKEN }}"
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USER }}/${DOCKER_IMAGE}:latest .
        docker push ${{ secrets.DOCKERHUB_USER }}/${DOCKER_IMAGE}:latest
    - name: Debug
      run: |
        ls -la

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DOCKER_SERVER_HOST }}
        username: ${{ secrets.DOCKER_SERVER_USER }}
        port: ${{ secrets.DOCKER_SERVER_PORT }}
        key: ${{ secrets.DOCKER_SERVER_KEY }}
        source: "rupbot"
        target: "/var/www"
    - name: Deploy to remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DOCKER_SERVER_HOST }}
        username: ${{ secrets.DOCKER_SERVER_USER }}
        port: ${{ secrets.DOCKER_SERVER_PORT }}
        key: ${{ secrets.DOCKER_SERVER_KEY }}
        script: |
          cd /var/www/rupbot
          docker ps -a
          docker compose pull
          docker compose down
          docker compose up -d
