# name: Deploy laravel application

# on:
#   push:
#     branches:
#       - main

# jobs:
#   buildandpush:
#     runs-on: ubuntu-latest
#     env:
#       DOCKER_IMAGE_VERSION: "v1.0.0"

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
    
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Login to Docker Hub
#       run: docker login -u devopssgp -p ${{ secrets.SGP_DOCKER_PASSWORD }}
    
#     - name: Build and push Docker image
#       run: |
#         docker build -t devopssgp/laravel-project:${DOCKER_IMAGE_VERSION} .
#         docker push devopssgp/laravel-project:${DOCKER_IMAGE_VERSION}

#     - name: Deploy to remote server
#       uses: appleboy/ssh-action@v1.0.1
#       with:
#         host: ${{ secrets.LARA_REMOTE_HOST }}
#         username: lara
#         password: ${{ secrets.LARA_PASSWORD }}
#         port: 22
#         script: |
#           docker stop $(docker ps -a -q)
#           docker rm -f $(docker ps -aq) 
#           docker pull devopssgp/laravel-project:v1.0.0
#           docker run -v /home/lara/larap1/.env:/var/www/html/.env -d -p 8000:80 devopssgp/laravel-project:v1.0.0